# Service para o Banco de Dados (Postgres)
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---

# Service para a API (com LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80         # Porta exposta externamente
    targetPort: 5000  # Porta onde a API está escutando no pod

---

# Service para o Web (acessível internamente)
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80         # Porta exposta internamente
    targetPort: 80    # Porta onde o nginx está escutando